source 'http://rubygems.org'

gem 'rails', '2.3.8'
gem 'mysql'
gem 'erubis'
gem 'jammit'
gem 'geokit'
gem 'httparty', '0.5.2'
gem 'nokogiri'
gem 'will_paginate'
gem 'friendly_id', '~> 2.3'
gem 'activerecord-tableless', :require => 'tableless'
gem 'searchlogic'
gem 'fleakr'
gem 'truncate_html'
gem 'paperclip'
gem 'rcov'
gem 'whenever'
gem 'hoptoad_notifier'
gem 'bossman'

group :test do
  gem 'shoulda', '2.10.3'
  gem 'phocus'
  gem 'machinist'
  gem 'faker'
  gem 'jferris-mocha', :require => false
  gem 'webmock'
  gem 'ruby-debug'
end
