require 'test_helper'

# ControllerTest generated by Typus, use it to test the extended admin functionality.
class Admin::HomeCommunitiesControllerTest < ActionController::TestCase
  context 'Admin::ApartmentCommunitiesController' do
    setup do
      @user = TypusUser.make
      login_typus_user @user
      @community1 = HomeCommunity.make
      @community2 = HomeCommunity.make
      @community1.destroy
    end
    
=begin
    context 'get #list_deleted' do
      setup do
        get :list_deleted
      end
      
      should_respond_with :success
      should_render_template :list_deleted
      should_assign_to :items
    end
=end

    context 'GET to #export_field_audit' do
      setup do
        get :export_field_audit
      end

      should respond_with(:success)
      should respond_with_content_type('text/csv')

      should 'respond with the correct Content-Disposition header' do
        @response.headers["Content-Disposition"].should == 'attachment; filename="home_communities_field_audit.csv"'
      end
    end
  end
end
