require 'test_helper'

# ControllerTest generated by Typus, use it to test the extended admin functionality.
class Admin::PagesControllerTest < ActionController::TestCase
  context 'Admin::PagesController' do
    setup do
      @user = TypusUser.make
      login_typus_user @user
      @page = Page.make
      @page2 = Page.make
      @page.destroy
    end
    
    context 'get #recover' do
      setup do
        get :recover, :id => @page.id
      end
      
      should_respond_with :redirect
      should_assign_to :page
      
      should_change 'Page count', :by => 1 do
        Page.count
      end
      
      should_change 'Page count', :by => -1 do
        Page::Archive.count
      end
    end
    
    context 'get #list_deleted' do
      setup do
        get :list_deleted
      end
      
      should_respond_with :success
      should_render_template :list_deleted
      should_assign_to :items
    end
  end
end