require 'test_helper'

# ControllerTest generated by Typus, use it to test the extended admin functionality.
class Admin::PhotosControllerTest < ActionController::TestCase
  context 'Admin::PhotosControllerTest' do
    setup do
      @user = TypusUser.make
      login_typus_user @user

      @photo = Photo.make
    end

    context 'POST to #update' do
      setup do
        post :update, :id => @photo.id, photo: { photo_group_id: @photo.photo_group_id }
      end

      should respond_with(:redirect)
      should redirect_to("the property's edit page") {
        "/admin/apartment_communities/edit/#{@photo.property.id}#photos"
      }
    end
  end
end
