require 'test_helper'

# ControllerTest generated by Typus, use it to test the extended admin functionality.
class Admin::StatesControllerTest < ActionController::TestCase
  context 'Admin::StatesController' do
    setup do
      @user = TypusUser.make
      login_typus_user @user
      @state = State.make
      @city = City.make(:state => @state)
      @community = ApartmentCommunity.make(:city => @city)
    end
    
    context '#relate for "featured_apartment_communities"' do
      setup do
        @request.env['HTTP_REFERER'] = "http://bozzuto.test/admin/states/edit/#{@state.id}"

        post :relate,
          :id      => @state.id,
          :related => {
            :relation => 'featured_apartment_communities',
            :id       => @community.id,
            :model    => 'ApartmentCommunity'
          }
      end
      
      should assign_to(:community)
      should respond_with(:redirect)
      
      it "changes featured to true" do
        @community.reload.featured?.should == true
      end
    end
    
    context 'with an existing featured community' do
      setup do
        @community.update_attribute(:featured, true)
      end
      
      context '#unrelate for "featured_apartment_communities"' do
        setup do
          @request.env['HTTP_REFERER'] = "http://bozzuto.test/admin/states/edit/#{@state.id}"

          get :unrelate,
              :id          => @state.id,
              :field       => 'featured_apartment_communities',
              :resource_id => @community.id,
              :resource    => 'ApartmentCommunity'
        end

        should assign_to(:community)
        should respond_with(:redirect)

        it "changes featured to false" do
          @community.reload.featured?.should == false
        end
      end
    end
  end
end
