# Controller generated by Typus, use it to extend admin functionality.
class Admin::AdSourcesController < Admin::MasterController

  private

  def generate_csv
    send_file Bozzuto::AdSourceCsv.new(:conditions => @conditions).file
  end
end
