# Controller generated by Typus, use it to extend admin functionality.
class Admin::ApartmentCommunitiesController < Admin::MasterController
  def list_deleted
    set_fields
    items_count = ApartmentCommunity::Archive.count
    items_per_page = ApartmentCommunity.typus_options_for(:per_page).to_i

    @pager = ::Paginator.new(items_count, items_per_page) do |offset, per_page|
      ApartmentCommunity::Archive.find(:all, :limit => per_page, :offset => offset, :order => 'title ASC').map {|item| 
        item.becomes(ApartmentCommunity)
      }
    end

    @items = @pager.page(params[:page])
    
    respond_to do |format|
      format.html
    end
  end
  
  def preview
    find_item
    redirect_to apartment_community_url(@item)
  end
end
