# Controller generated by Typus, use it to extend admin functionality.
class Admin::AreaMembershipsController < Admin::MasterController
  def update
    super

    area = @item.area

    # Cancel the previous redirect
    @_response_body = nil

    redirect_to(
      :controller => "admin/#{area.class.to_s.tableize}",
      :action     => :edit,
      :id         => area.id,
      :anchor     => 'area_memberships'
    )
  end
end
