# Controller generated by Typus, use it to extend admin functionality.
class Admin::BuzzesController < Admin::MasterController

  private

  def generate_csv
    send_file Bozzuto::BuzzCsv.new(:conditions => @conditions).file
  end
end
