# Controller generated by Typus, use it to extend admin functionality.
class Admin::DnrConfigurationsController < Admin::MasterController

  before_filter :override_resource, :only => [:update, :create]

  def override_resource
    params[:resource] = 'property'
  end
end
