# Controller generated by Typus, use it to extend admin functionality.
class Admin::FeedsController < Admin::MasterController
  after_filter :refresh_feed, :only => [:create, :update]


  protected

  def refresh_feed
    @item.refresh! unless @item.new_record?
  end
end
