# Controller generated by Typus, use it to extend admin functionality.
class Admin::GreenPackageItemsController < Admin::MasterController
  def index
    redirect_to admin_dashboard_path
  end


  private

  def actions
  end
  helper_method :actions
end
