# Controller generated by Typus, use it to extend admin functionality.
class Admin::HomeCommunitiesController < Admin::MasterController
  def list_deleted
    set_fields
    items_count = HomeCommunity::Archive.count
    items_per_page = HomeCommunity.typus_options_for(:per_page).to_i

    @pager = ::Paginator.new(items_count, items_per_page) do |offset, per_page|
      HomeCommunity::Archive.find(:all, :limit => per_page, :offset => offset, :order => 'title ASC').map {|item| 
        item.becomes(HomeCommunity)
      }
    end

    @items = @pager.page(page_number)
    
    respond_to do |format|
      format.html
    end
  end
  
  def preview
    find_item
    redirect_to home_community_url(@item)
  end

  def export_field_audit
    csv_string = Bozzuto::HomeCommunityFieldAudit.audit_csv
    send_data csv_string, :filename => "home_communities_field_audit.csv", :type => :csv
  end
end
