# Controller generated by Typus, use it to extend admin functionality.
class Admin::NeighborhoodMembershipsController < Admin::MasterController
  def update
    super

    neighborhood = @item.neighborhood

    # Cancel the previous redirect
    @_response_body = nil

    redirect_to(
      :controller => "admin/#{neighborhood.class.to_s.tableize}",
      :action     => :edit,
      :id         => neighborhood.id,
      :anchor     => 'neighborhood_memberships'
    )
  end
end
