# Controller generated by Typus, use it to extend admin functionality.
class Admin::PhotosController < Admin::MasterController

  def update
    super

    # update_attributes(params[:photo]) not saving the photo group id
    # Only explicitly setting the photo group to a photo group seems to work
    @item.photo_group = PhotoGroup.find(params[:photo][:photo_group_id])
    @item.save

    property = @item.property

    # Cancel the previous redirect
    @_response_body = nil

    redirect_to(
      :controller => "admin/#{property.class.to_s.tableize}",
      :action     => :edit,
      :id         => property.id,
      :anchor     => 'photos'
    )
  end
end
