# Controller generated by Typus, use it to extend admin functionality.
class Admin::PhotosController < Admin::MasterController

  def update
    super

    property = @item.property

    # Cancel the previous redirect
    @_response_body = nil

    redirect_to(
      :controller => "admin/#{property.class.to_s.tableize}",
      :action     => :edit,
      :id         => property.id,
      :anchor     => 'photos'
    )
  end
end
