# Controller generated by Typus, use it to extend admin functionality.
class Admin::PropertiesController < Admin::MasterController
  def edit
    property = Property.find(params[:id])
    redirect_to :controller => "admin/#{property.class.to_s.tableize}",
                :action => :edit, :id => params[:id]
  end

  def show
    property = Property.find(params[:id])
    redirect_to :controller => "admin/#{property.class.to_s.tableize}",
                :action => :show, :id => params[:id]
  end
end
