# Controller generated by Typus, use it to extend admin functionality.
class Admin::PropertiesController < Admin::MasterController
  def edit
    property = Property.find(params[:id])
    redirect_to :controller => "admin/#{property.class.to_s.tableize}",
                :action => :edit, :id => params[:id]
  end

  def show
    property = Property.find(params[:id])
    redirect_to :controller => "admin/#{property.class.to_s.tableize}",
                :action => :show, :id => params[:id]
  end
  
  def recover
    Property.restore_all(["id = ?", params[:id]])
    @property = Property.find(params[:id])
    if (@property.is_a?(Community) && @property.featured?) || @property.is_a?(Project)
      @property.send(:assume_bottom_position)
    end
    flash[:success] = _("{{model}} successfully recovered.", 
                        :model => @resource[:human_name])
    redirect_to request.referer || admin_dashboard_path
  end
end
