# Controller generated by Typus, use it to extend admin functionality.
class Admin::SeoMetadataController < Admin::MasterController
  def create_with_back_to
    resource_class = params[:resource].classify.constantize

    @item.save

    flash[:success] = _("{{item}} successfully created.", :item => @item.class.typus_human_name)

    redirect_to params[:back_to]
  end
end
