# Controller generated by Typus, use it to extend admin functionality.
class Admin::UnderConstructionLeadsController < Admin::MasterController

  def destroy_multiple
    if params[:ids].present?
      UnderConstructionLead.destroy(params[:ids])
    end
    redirect_to :action => :index
  end

  private

  def generate_csv
    send_file Bozzuto::UnderConstructionLeadCsv.new(:conditions => @conditions).file
  end
end
