# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  ApartmentCommunity: create, read, update, delete
  Award: create, read, update, delete
  City: create, read, update, delete
  County: create, read, update, delete
  FloorPlanGroup: create, read, update, delete
  FloorPlan: create, read, update, delete
  HomeCommunity: create, read, update, delete
  NewsPost: create, read, update, delete
  Page: create, read, update, delete
  Photo: create, read, update, delete
  Project: create, read, update, delete
  ProjectDataPoint: create, read, update, delete
  ProjectUpdate: create, read, update, delete
  Section: read, update
  State: create, read, update, delete
  Testimonial: create, read, update, delete
  YelpFeed: create, read, update, delete
