# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  ApartmentCommunity: create, read, update, delete
  ApartmentFloorPlan: create, read, update, delete
  ApartmentFloorPlanGroup: read
  Award: create, read, update, delete
  BodySlide: create, read, update, delete
  BodySlideshow: create, read, update, delete
  City: create, read, update, delete
  County: create, read, update, delete
  Feed: create, read, update, delete
  Home: create, read, update, delete
  HomeCommunity: create, read, update, delete
  HomeFloorPlan: create, read, update, delete
  HomePage: read, update
  HomePageSlide: create, read, update, delete
  LandingPage: create, read, update, delete
  Leader: create, read, update, delete
  LeadershipGroup: create, read, update, delete
  MastheadSlide: create, read, update, delete
  MastheadSlideshow: create, read, update, delete
  NewsPost: create, read, update, delete
  Page: create, read, update, delete
  Photo: create, read, update, delete
  PhotoSet: create, read, update, delete
  Project: create, read, update, delete
  ProjectCategory: create, read, update, delete
  ProjectDataPoint: create, read, update, delete
  ProjectUpdate: create, read, update, delete
  Property: create, read, update, delete
  PropertyFeature: create, read, update, delete
  PropertyMiniSlide: create, read, update, delete
  PropertyMiniSlideshow: create, read, update, delete
  PropertySlide: create, read, update, delete
  PropertySlideshow: create, read, update, delete
  Section: read, update
  State: create, read, update, delete
  Testimonial: create, read, update, delete
  Video: create, read, update, delete
