# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.
#
ApartmentCommunity:
  fields:
    default: title, street_address, city
    list: title, street_address, city
    form: title, subtitle, city, elite, smart_share, smart_rent, green, non_smoking, website_url, video_url, facebook_url, twitter_handle, promo_image, promo_url, latitude, longitude, street_address, yelp_feed, overview_text, features_text, neighborhood_text, promotions_text, contact_text
  order_by:
  relationships: city, floor_plan_groups, photos, yelp_feed
  filters:
  search: title
  application: Community

Award:
  fields:
    default: title, published, published_at, section
    list: title, published, published_at, section
    form: title, body, published, published_at, section
  order_by: 
  relationships: section
  filters: 
  search: title
  application: Bozzuto

City:
  fields:
    default: name, state
    list: name, state
    form: name, state, county
  order_by:
  relationships: apartment_communities, county, state
  filters:
  search: name
  application: Bozzuto

County:
  fields:
    default: name, state
    list: name, state
    form: name, state
  order_by:
  relationships: state
  filters:
  search: name
  application: Bozzuto

FloorPlanGroup:
  fields:
    default: name, position
    list: apartment_community, name, position
    form: apartment_community, name
  order_by: apartment_community_id, position
  relationships: apartment_community, floor_plans
  search: name
  application: Community

FloorPlan:
  fields:
    default: image, bedrooms, bathrooms, min_square_feet, max_square_feet, position
    list: image, bedrooms, bathrooms, min_square_feet, max_square_feet, position
    form: image, availability_url, bedrooms, bathrooms, min_market_rent, max_market_rent, min_effective_rent, max_effective_rent, min_square_feet, max_square_feet, floor_plan_group
  order_by: position
  relationships: floor_plan_group
  filters:
  search:
  application: Community

HomeCommunity:
  fields:
    default: title, street_address, city
    list: title, street_address, city
    form: title, subtitle, elite, smart_share, smart_rent, green, non_smoking, website_url, video_url, facebook_url, twitter_handle, promo_image, promo_url, latitude, longitude, street_address, overview_text, features_text, neighborhood_text, promotions_text, contact_text, yelp_feed_id, availability_url, section_id, city
  order_by: 
  relationships: city
  filters: 
  search: title
  application: Community

NewsPost:
  fields:
    default: title, published, published_at
    list: title, published, published_at
    form: title, body, published, published_at, section
  order_by: -published_at
  relationships: section
  filters:
  search:
  application: Bozzuto

Page:
  fields:
    default: formatted_title
    list: formatted_title, section
    form: title, body, section, parent
  order_by: section_id, lft
  relationships: parent, section
  filters:
  search: title
  application: Bozzuto

Photo:
  fields:
    default: image, caption, apartment_community
    list: image, caption, apartment_community
    form: image, caption, apartment_community
  order_by:
  relationships: apartment_community
  filters:
  search:
  application: Community

Project:
  fields:
    default: title, street_address, city
    list: title, street_address, city
    form: title, subtitle, section, website_url, video_url, latitude, longitude, street_address, overview_text, city
  order_by: 
  relationships: city, section, data_points, updates
  filters: 
  search: title
  application: Bozzuto

ProjectDataPoint:
  fields:
    default: name, data, position
    list: name, data, position
    form: name, data, project
  order_by: position
  relationships: project
  filters: 
  search: name
  application: 

ProjectUpdate:
  fields:
    default: published_at, published
    list: published_at, published
    form: body, published, published_at, project
  order_by: 
  relationships: project
  filters: 
  search: 
  application: 

Section:
  fields:
    default: title
    list: title
    form: title
  options:
    read_only: title
  order_by: title
  relationships: pages, news_posts, testimonials, awards, projects
  filters:
  search:
  application: Bozzuto

State:
  fields:
    default: code, name
    list: code, name
    form: code, name
  order_by:
  relationships: cities
  filters:
  search: name
  application: Bozzuto

Testimonial:
  fields:
    default: name, title, quote
    list: name, title, quote
    form: name, title, quote, section
  order_by:
  relationships: section
  filters:
  search: name
  application: Bozzuto

YelpFeed:
  fields:
    default: url
    list: url
    form: url
  order_by:
  relationships: apartment_communities
  filters:
  search:
  application: Community

