# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.
#
ApartmentCommunity:
  fields:
    default: title, published, street_address, city
    list: title, published, street_address, city
    form: title, short_title, street_address, city, county, phone_number, latitude, longitude, ufollowup_id, website_url, video_url, facebook_url, twitter_handle, brochure_link_text, brochure_type, brochure, brochure_url, local_info_feed, listing_image, listing_title, listing_text, meta_title, meta_description, meta_keywords, overview_title, overview_text, overview_bullet_1, overview_bullet_2, overview_bullet_3, promo, features_meta_title, features_meta_description, features_meta_keywords, features_1_title, features_1_text, features_2_title, features_2_text, features_3_title, features_3_text, media_meta_title, media_meta_description, media_meta_keywords, floor_plans_meta_title, floor_plans_meta_description, floor_plans_meta_keywords, neighborhood_meta_title, neighborhood_meta_description, neighborhood_meta_keywords, neighborhood_text, contact_meta_title, contact_meta_description, contact_meta_keywords, contact_text, show_lead_2_lease, lead_2_lease_email, published
    options:
      ckeditor: listing_text, overview_text, features_1_text, features_2_text, features_3_text, neighborhood_text, promotions_text, contact_text
      booleans:
        published: ['Yes', 'No']
      selectors: brochure_type
      destroy_related: PropertySlideshow, PropertyMiniSlideshow, Video, PhotoSet, ApartmentFloorPlan
  order_by: title
  relationships: property_features, city, county, local_info_feed, slideshow, videos, photo_set, floor_plans, promo
  filters:
  search: title, street_address
  application: Properties

ApartmentFloorPlan:
  fields:
    default: name, bedrooms, bathrooms, featured, position
    list: actual_image, bedrooms, bathrooms, position
    form: apartment_community, name, featured, image_type, image_url, image, availability_url, bedrooms, bathrooms, min_square_feet, max_square_feet, min_market_rent, max_market_rent, min_effective_rent, max_effective_rent, floor_plan_group
    options:
      selectors: image_type
      booleans:
        featured: ['Yes', 'No']
  order_by: floor_plan_group_id, position
  relationships: floor_plan_group
  filters:
  search:
  application:

ApartmentFloorPlanGroup:
  fields:
    default: name, position
    list: name, position
    form: name
  order_by: position
  relationships: floor_plans
  search: name
  application:

Award:
  fields:
    default: title, published, published_at
    list: title, published, published_at
    form: title, image, body, published, published_at
    options:
      ckeditor: body
      booleans:
        published: ['Yes', 'No']
  order_by: -published_at
  relationships: sections
  filters:
  search: title
  application: News & Press

BodySlide:
  fields:
    default: image, position
    list: image, position
    form: image, link_url, property, body_slideshow
  order_by: position
  relationships: body_slideshow, property
  filters:
  search:
  application:

BodySlideshow:
  fields:
    default: name
    list: name, page
    form: name, page
    options:
      destroy_related: BodySlide
  order_by:
  relationships: page, slides
  filters:
  search: name
  application:

City:
  fields:
    default: name, state
    list: name, state
    form: name, state
  order_by: name
  relationships: apartment_communities, counties, state
  filters:
  search: name
  application: Geography

ContactTopic:
  fields:
    default: topic, position
    list: topic, position
    form: topic, body, recipients, section
    options:
      ckeditor: body
  order_by: position
  relationships:
  filters:
  search:
  application: Content

County:
  fields:
    default: name, state
    list: name, state
    form: name, state
  order_by: name
  relationships: state, cities
  filters:
  search: name
  application: Geography

Feed:
  fields:
    default: name, url
    list: name, url
    form: name, url
  order_by:
  relationships:
  filters:
  search:
  application:

Home:
  fields:
    default: name, bedrooms, bathrooms, featured, position
    list: name, bedrooms, bathrooms, home_community, position
    form: name, bedrooms, bathrooms, featured, home_community
    options:
      destroy_related: HomeFloorPlan
  order_by: position
  relationships: home_community, floor_plans
  filters:
  search: name
  application:

HomeCommunity:
  fields:
    default: title, published, street_address, city
    list: title, published, street_address, city
    form: title, short_title, street_address, city, county, phone_number, latitude, longitude, ufollowup_id, website_url, video_url, facebook_url, twitter_handle, brochure_link_text, brochure_type, brochure, brochure_url, local_info_feed, listing_image, listing_promo, listing_title, listing_text, latitude, longitude, meta_title, meta_description, meta_keywords, overview_title, overview_text, overview_bullet_1, overview_bullet_2, overview_bullet_3, features_meta_title, features_meta_description, features_meta_keywords, features_1_title, features_1_text, features_2_title, features_2_text, features_3_title, features_3_text, media_meta_title, media_meta_description, media_meta_keywords, media_meta_description, floor_plans_meta_title, floor_plans_meta_description, floor_plans_meta_keywords, neighborhood_meta_title, neighborhood_meta_description, neighborhood_meta_keywords, neighborhood_text, contact_meta_title, contact_meta_description, contact_meta_keywords, contact_text, published, promo
    options:
      ckeditor: listing_text, overview_text, features_1_text, features_2_text, features_3_text, neighborhood_text, promotions_text, contact_text
      booleans:
        published: ['Yes', 'No']
      selectors: brochure_type
      destroy_related: PropertySlideshow, PropertyMiniSlideshow, Home, Video, PhotoSet
  order_by: title
  relationships: property_features, city, county, slideshow, videos, photo_set, homes, local_info_feed, promo
  filters:
  search: title
  application: Properties

HomeFloorPlan:
  fields:
    default: name, image, position
    list: name, position
    form: name, image, home
  order_by: position
  relationships: home
  filters:
  search: name
  application:

HomePage:
  fields:
    default:
    list:
    form: meta_title, meta_description, meta_keywords, body, mini_slideshow
    options:
      ckeditor: body
      destroy_related: HomePageSlide
  order_by:
  relationships: slides, mini_slideshow
  filters:
  search:
  application: Content

HomePageSlide:
  fields:
    default: image, position
    list: image, position
    form: image
  order_by: position
  relationships: home_page
  filters:
  search:
  application:

LandingPage:
  fields:
    default: title, state
    list: title, state
    form: title, state, meta_title, meta_description, meta_keywords, masthead_body, masthead_image, promo, secondary_title, secondary_body
    options:
      ckeditor: masthead_body, secondary_body
  order_by:
  relationships: state, popular_properties, apartment_communities, featured_apartment_communities, home_communities, projects, promo
  filters:
  search: title
  application: Geography

Leader:
  fields:
    default: name, title, company
    list: name, title, company, leadership_group, position
    relationship: name, title, company, position
    form: leadership_group, name, title, company, bio, image
  order_by: leadership_group_id, position
  relationships: leadership_group
  application: Leaders

LeadershipGroup:
  fields:
    default: name
    list: name, position
  order_by: position
  relationships: leaders
  application: Leaders

MastheadSlide:
  fields:
    default: image, image_link, position
    list: image, image_link, position
    form: body, slide_type, image, image_link, sidebar_text, mini_slideshow, quote, quote_attribution, quote_job_title, quote_company, masthead_slideshow
    options:
      ckeditor: body, sidebar_text, quote
      selectors: slide_type
  order_by: position
  relationships: mini_slideshow, masthead_slideshow
  filters:
  search:
  application:

MastheadSlideshow:
  fields:
    default: name
    list: name, page
    form: name, page
    options:
      destroy_related: MastheadSlide
  order_by:
  relationships: page, slides
  filters:
  search: name
  application:

NewsPost:
  fields:
    default: title, published, published_at
    list: title, published, published_at
    form: title, meta_title, meta_description, meta_keywords, image, body, published, published_at
    options:
      ckeditor: body
      booleans:
        published: ['Yes', 'No']
  order_by: -published_at
  relationships: sections
  filters:
  search:
  application: News & Press

Page:
  fields:
    default: formatted_title, position
    list: formatted_title, section, position
    form: title, meta_title, meta_description, meta_keywords, body, section, parent
    options:
      ckeditor: body
      destroy_related: MastheadSlideshow, BodySlideshow
  order_by: section_id, lft
  relationships: parent, section, masthead_slideshow, body_slideshow
  filters:
  search: title
  application:
  options:

Photo:
  fields:
    default: image, caption, apartment_community
    list: image, caption, apartment_community
    form: image, caption, apartment_community
  order_by:
  relationships: apartment_community
  filters:
  search:
  application:

PhotoSet:
  fields:
    default: title, flickr_set_number
    list: title, flickr_set_number, property
    form: flickr_set_number, needs_sync, property
    options:
      booleans:
        needs_sync: ['Yes', 'No']
  order_by:
  relationships: property
  filters:
  search: title
  application:

PressRelease:
  fields:
    default: title, published, published_at
    list: title, published, published_at
    form: title, body, published, published_at, meta_title, meta_description, meta_keywords
    options:
      ckeditor: body
      booleans:
        published: ['Yes', 'No']
  order_by: -published_at
  relationships: sections
  filters:
  search: title, body
  application: News & Press

Project:
  fields:
    default: title, published, street_address, city
    list: title, published, street_address, city, section
    relationship: title, published, street_address, city, position
    form: title, short_title, has_completion_date, completion_date, meta_title, meta_description, meta_keywords, section, street_address, city, county, latitude, longitude, website_url, video_url, brochure_link_text, brochure_type, brochure, brochure_url, listing_image, listing_title, listing_text, overview_text, published
    options:
      ckeditor: listing_text, overview_text
      booleans:
        published: ['Yes', 'No']
      selectors: brochure_type
      destroy_related: PropertySlideshow, PropertyMiniSlideshow, ProjectDataPoint, ProjectUpdate
  options:
    start_year: 1990
  order_by: section_id, position
  relationships: city, section, slideshow, data_points, updates, project_categories
  filters:
  search: title
  application: Properties

ProjectCategory:
  fields:
    default: title
    list: title, position
    form: title
  order_by: position
  relationships: projects
  filters:
  search: title
  application: Properties

ProjectDataPoint:
  fields:
    default: name, data, position
    list: name, data, position
    form: name, data, project
  order_by: position
  relationships: project
  filters:
  search: name
  application:

ProjectUpdate:
  fields:
    default: published_at, published
    list: published_at, published
    form: image, image_title, image_description, body, published, published_at, project
    options:
      ckeditor: body
      booleans:
        published: ['Yes', 'No']
  order_by: -published_at
  relationships: project
  filters:
  search:
  application:

Promo:
  fields:
    default: title
    list: title
    form: title, subtitle, link_url
  order_by: title
  relationships: apartment_communities, home_communities, landing_pages
  filters:
  search: title, subtitle, link_url
  application: Content

Property:
  fields:
    default: title, street_address, city
    list:
    form: property_type, title, street_address, city
    options:
      selectors: brochure_type, property_type
  order_by: title
  relationships: slideshow, video, photo_set
  filters:
  search:
  application:

PropertyFeature:
  fields:
    default: name, icon
    list: name, icon, position
    form: name, icon, description, show_on_search_page
  order_by: position
  relationships:
  filters:
  search: name
  application: Properties

MiniSlide:
  fields:
    default: image, position
    list: image, position
    form: image, mini_slideshow
  order_by: position
  relationships: mini_slideshow
  filters:
  search:
  application:

MiniSlideshow:
  fields:
    default: title
    list: title
    form: title, subtitle, link_url
    options:
      destroy_related: MiniSlide
  order_by:
  relationships: slides
  filters:
  search:
  application:

PropertySlide:
  fields:
    default: image, position, property_slideshow
    list: image, position, property_slideshow
    form: image, caption, property_slideshow
  order_by: position
  relationships: property_slideshow
  filters:
  search:
  application:

PropertySlideshow:
  fields:
    default: name, property
    list: name, property
    form: name, property
    options:
      destroy_related: PropertySlide
  order_by:
  relationships: property, slides
  filters:
  search: name
  application:

Section:
  fields:
    default: title
    list: title
    form: title, left_montage_image, middle_montage_image, right_montage_image
    options:
      read_only: title
      destroy_related: Page, NewsPost, Testimonial, Project, Award, PressRelease
  order_by: title
  relationships: pages, projects, testimonials, awards, news_posts, press_releases
  filters:
  search:
  application: Content

Snippet:
  fields:
    default: name
    list: name
    form: name, body
    options:
      ckeditor: body
  order_by: name
  search: name, body
  application: Content

State:
  fields:
    default: name, code
    list: name, code
    form: name, code
  order_by: name
  relationships: cities, counties
  filters:
  search: name
  application: Geography

Testimonial:
  fields:
    default: name, title, quote
    list: name, title, quote
    form: name, title, quote, section
    options:
      ckeditor: quote
  order_by:
  relationships: section
  filters:
  search: name
  application: Content

Video:
  fields:
    default: url, position
    list: image, position, property
    form: image, url, property
  order_by: position
  relationships: property
  filters:
  search:
  application:
