# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  City: create, read, update, delete
  County: create, read, update, delete
  Community: create, read, update, delete
  FloorPlanGroup: create, read, update, delete
  FloorPlan: create, read, update, delete
  Photo: create, read, update, delete
  State: create, read, update, delete
