# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  ApartmentCommunity: create, read, update, delete, list_deleted, list_duplicates, preview, merge, begin_merge, end_merge
  ApartmentContactConfiguration: create, read, update, delete
  ApartmentFloorPlan: create, read, update, delete
  ApartmentFloorPlanGroup: read
  Award: create, read, update, delete
  BodySlide: create, read, update, delete
  BodySlideshow: create, read, update, delete
  BozzutoBlogPost: create, read, update, delete
  Buzz: read, delete
  CareersEntry: create, read, update, delete
  Carousel: create, read, update, delete
  CarouselPanel: create, read, update, delete
  City: create, read, update, delete
  ContactTopic: create, read, update, delete
  ConversionConfiguration: create, read, update, delete
  County: create, read, update, delete
  DnrConfiguration: create, read, update, delete
  DnrReferrer: create, read, update, delete
  Feed: create, read, update, delete
  GreenFeature: create, read, update, delete
  GreenPackage: create, read, update, delete
  Home: create, read, update, delete
  HomeCommunity: create, read, update, delete, list_deleted, preview
  HomeFloorPlan: create, read, update, delete
  HomePage: read, update
  HomePageSlide: create, read, update, delete
  LandingPage: create, read, update, delete
  LandingPagePopularOrdering : read, update, delete
  LassoAccount: create, read, update, delete
  Leader: create, read, update, delete
  LeadershipGroup: create, read, update, delete
  MastheadSlide: create, read, update, delete
  MastheadSlideshow: create, read, update, delete
  MediaplexTag: create, read, update, delete
  MiniSlide: create, read, update, delete
  MiniSlideshow: create, read, update, delete
  NewsPost: create, read, update, delete
  Page: create, read, update, delete, preview, list_deleted, recover
  Photo: create, read, update, delete
  PhotoSet: create, read, update, delete
  PressRelease: create, read, update, delete
  Project: create, read, update, delete, list_deleted
  ProjectCategory: create, read, update, delete
  ProjectDataPoint: create, read, update, delete
  ProjectUpdate: create, read, update, delete
  Promo: create, read, update, delete
  Property: create, read, update, delete, recover
  PropertyContactPage: create, read, update, delete
  PropertyFeature: create, read, update, delete
  PropertyFeaturesPage: create, read, update, delete
  PropertyNeighborhoodPage: create, read, update, delete
  PropertyToursPage: create, read, update, delete
  PropertySlide: create, read, update, delete
  PropertySlideshow: create, read, update, delete
  Publication: create, read, update, delete
  RankCategory: create, read, update, delete
  Rank: create, read, update, delete
  Section: read, update
  Snippet: create, read, update, delete
  State: create, read, update, delete
  Testimonial: create, read, update, delete
  TwitterAccount: create, read, update, delete
  UnderConstructionLead: read, delete
  Video: create, read, update, delete
