# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.
#
ApartmentCommunity:
  fields:
    default: title, street_address, city
    list: title, street_address, city
    form: title, subtitle, street_address, city, county, latitude, longitude, website_url, video_url, facebook_url, twitter_handle, yelp_feed, elite, smart_share, smart_rent, green, non_smoking, fitness_center, metro_access, pet_friendly, washer_and_dryer, brand_new, listing_image, listing_title, listing_text, overview_text, features_text, neighborhood_text, contact_text
    options:
      ckeditor: listing_text, overview_text, features_text, neighborhood_text, contact_text
  order_by:
  relationships: city, county, yelp_feed, slideshow, floor_plans
  filters:
  search: title, street_address
  application: Properties

Award:
  fields:
    default: title, published, published_at, section
    list: title, published, published_at, section
    form: title, body, published, published_at, section
    options:
      ckeditor: body
  order_by: 
  relationships: section
  filters:
  search: title
  application: Content

City:
  fields:
    default: name, state
    list: name, state
    form: name, state
  order_by:
  relationships: apartment_communities, counties, state
  filters:
  search: name
  application: Geography

County:
  fields:
    default: name, state
    list: name, state
    form: name, state
  order_by: name
  relationships: state, cities
  filters:
  search: name
  application: Geography

FloorPlanGroup:
  fields:
    default: name, position
    list: name, position
    form: name
  order_by: position
  relationships: floor_plans
  search: name
  application:

FloorPlan:
  fields:
    default: image, bedrooms, bathrooms, min_square_feet, max_square_feet, position
    list: image, bedrooms, bathrooms, min_square_feet, max_square_feet, position
    form: image, availability_url, bedrooms, bathrooms, min_square_feet, max_square_feet, min_market_rent, max_market_rent, min_effective_rent, max_effective_rent, floor_plan_group
  order_by: floor_plan_group_id, position
  relationships: floor_plan_group
  filters:
  search:
  application:

Home:
  fields:
    default: name, bedrooms, bathrooms, featured, position
    list: name, bedrooms, bathrooms, home_community, position
    form: name, bedrooms, bathrooms, featured, home_community
  order_by: position
  relationships: home_community, floor_plans
  filters:
  search: name
  application:

HomeCommunity:
  fields:
    default: title, street_address, city
    list: title, street_address, city
    form: title, subtitle, street_address, city, county, latitude, longitude, website_url, video_url, facebook_url, twitter_handle, yelp_feed, elite, smart_share, smart_rent, green, non_smoking, listing_image, listing_title, listing_text, latitude, longitude, overview_text, features_text, neighborhood_text, contact_text
    options:
      ckeditor: listing_text, overview_text, features_text, neighborhood_text, contact_text
  order_by: 
  relationships: city, county, homes, yelp_feed
  filters:
  search: title
  application: Properties

HomeFloorPlan:
  fields:
    default: name, image, position
    list: name, position
    form: name, image, home
  order_by: position
  relationships: home
  filters:
  search: name
  application:

NewsPost:
  fields:
    default: title, published, published_at
    list: title, published, published_at
    form: title, body, published, published_at, section
    options:
      ckeditor: body
  order_by: -published_at
  relationships: section
  filters:
  search:
  application: Content

Page:
  fields:
    default: formatted_title
    list: formatted_title, section
    form: title, body, section, parent
    options:
      ckeditor: body
  order_by: section_id, lft
  relationships: parent, section
  filters:
  search: title
  application: Content

Photo:
  fields:
    default: image, caption, apartment_community
    list: image, caption, apartment_community
    form: image, caption, apartment_community
  order_by:
  relationships: apartment_community
  filters:
  search:
  application:

Project:
  fields:
    default: title, street_address, city
    list: title, street_address, city
    form: title, section, street_address, city, county, latitude, longitude, website_url, video_url, listing_image, listing_title, listing_text, overview_text
    options:
      ckeditor: listing_text, overview_text
  order_by: 
  relationships: city, section, data_points, updates
  filters:
  search: title
  application: Properties

ProjectDataPoint:
  fields:
    default: name, data, position
    list: name, data, position
    form: name, data, project
  order_by: position
  relationships: project
  filters:
  search: name
  application:

ProjectUpdate:
  fields:
    default: published_at, published
    list: published_at, published
    form: body, published, published_at, project
    options:
      ckeditor: body
  order_by: 
  relationships: project
  filters:
  search:
  application:

Property:
  fields:
    default:
    list:
    form:
  order_by:
  relationships: slideshow
  filters:
  search:
  application:

PropertySlide:
  fields:
    default: image, position, property_slideshow
    list: image, position, property_slideshow
    form: image, caption, property_slideshow
    options:
      ckeditor: caption
  order_by: position
  relationships: property_slideshow
  filters: 
  search: 
  application: 

PropertySlideshow:
  fields:
    default: name, property
    list: name, property
    form: name, property
  order_by: 
  relationships: property, slides
  filters: 
  search: name
  application: 

Section:
  fields:
    default: title
    list: title
    form: title, left_montage_image, middle_montage_image, right_montage_image
  order_by: title
  relationships: pages, news_posts, testimonials, awards, projects
  filters:
  search:
  application: Content

State:
  fields:
    default: name, code
    list: name, code
    form: name, code
  order_by: name
  relationships: cities, counties
  filters:
  search: name
  application: Geography

Testimonial:
  fields:
    default: name, title, quote
    list: name, title, quote
    form: name, title, quote, section
    options:
      ckeditor: quote
  order_by:
  relationships: section
  filters:
  search: name
  application: Content

YelpFeed:
  fields:
    default: url
    list: url
    form: url
  order_by:
  relationships: apartment_communities
  filters:
  search:
  application:

