# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.
#
ApartmentCommunity:
  fields:
    default: title, street_address, city
    list: title, street_address, city
    form: title, subtitle, street_address, city, county, elite, smart_share, smart_rent, green, non_smoking, website_url, video_url, facebook_url, twitter_handle, promo_image, promo_url, latitude, longitude, yelp_feed, overview_text, features_text, neighborhood_text, promotions_text, contact_text
  order_by:
  relationships: city, county, floor_plans, yelp_feed
  filters:
  search: title
  application: Properties

Award:
  fields:
    default: title, published, published_at, section
    list: title, published, published_at, section
    form: title, body, published, published_at, section
  order_by: 
  relationships: section
  filters: 
  search: title
  application: Content

City:
  fields:
    default: name, state
    list: name, state
    form: name, state, county
  order_by:
  relationships: apartment_communities, county, state
  filters:
  search: name
  application: Properties

County:
  fields:
    default: name, state
    list: name, state
    form: name, state
  order_by: name
  relationships: state
  filters:
  search: name
  application: Properties

FloorPlanGroup:
  fields:
    default: name, position
    list: apartment_community, name, position
    form: apartment_community, name
  order_by: apartment_community_id, position
  relationships: apartment_community, floor_plans
  search: name
  application: 

FloorPlan:
  fields:
    default: image, bedrooms, bathrooms, min_square_feet, max_square_feet, position
    list: image, bedrooms, bathrooms, min_square_feet, max_square_feet, position
    form: image, availability_url, bedrooms, bathrooms, min_market_rent, max_market_rent, min_effective_rent, max_effective_rent, min_square_feet, max_square_feet, floor_plan_group
  order_by: position
  relationships: floor_plan_group
  filters:
  search:
  application: 

Home:
  fields:
    default: name, bedrooms, bathrooms, position
    list: name, bedrooms, bathrooms, home_community, position
    form: name, bedrooms, bathrooms, home_community
  order_by: position
  relationships: home_community
  filters: 
  search: name
  application: 

HomeCommunity:
  fields:
    default: title, street_address, city
    list: title, street_address, city
    form: title, subtitle, street_address, city, county, elite, smart_share, smart_rent, green, non_smoking, website_url, video_url, facebook_url, twitter_handle, promo_image, promo_url, latitude, longitude, overview_text, features_text, neighborhood_text, promotions_text, contact_text, yelp_feed
  order_by: 
  relationships: city, county, homes, yelp_feed
  filters: 
  search: title
  application: Properties

NewsPost:
  fields:
    default: title, published, published_at
    list: title, published, published_at
    form: title, body, published, published_at, section
  order_by: -published_at
  relationships: section
  filters:
  search:
  application: Content

Page:
  fields:
    default: formatted_title
    list: formatted_title, section
    form: title, body, section, parent
  order_by: section_id, lft
  relationships: parent, section
  filters:
  search: title
  application: Content

Photo:
  fields:
    default: image, caption, apartment_community
    list: image, caption, apartment_community
    form: image, caption, apartment_community
  order_by:
  relationships: apartment_community
  filters:
  search:
  application: 

Project:
  fields:
    default: title, street_address, city
    list: title, street_address, city
    form: title, subtitle, section, website_url, video_url, latitude, longitude, street_address, overview_text, city
  order_by: 
  relationships: city, section, data_points, updates
  filters: 
  search: title
  application: Properties

ProjectDataPoint:
  fields:
    default: name, data, position
    list: name, data, position
    form: name, data, project
  order_by: position
  relationships: project
  filters: 
  search: name
  application: 

ProjectUpdate:
  fields:
    default: published_at, published
    list: published_at, published
    form: body, published, published_at, project
  order_by: 
  relationships: project
  filters: 
  search: 
  application: 

Section:
  fields:
    default: title
    list: title
    form: title, left_montage_image, middle_montage_image, right_montage_image
  options:
    read_only: title
  order_by: title
  relationships: pages, news_posts, testimonials, awards, projects
  filters:
  search:
  application: Content

State:
  fields:
    default: code, name
    list: code, name
    form: code, name
  order_by:
  relationships: cities
  filters:
  search: name
  application: Properties

Testimonial:
  fields:
    default: name, title, quote
    list: name, title, quote
    form: name, title, quote, section
  order_by:
  relationships: section
  filters:
  search: name
  application: Content

YelpFeed:
  fields:
    default: url
    list: url
    form: url
  order_by:
  relationships: apartment_communities
  filters:
  search:
  application: Properties

