# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.
#
ApartmentCommunity:
  fields:
    default: title, published, street_address, city
    list: title, published, street_address, city
    form: title, short_title, meta_title, meta_description, meta_keywords, street_address, city, county, phone_number, latitude, longitude, website_url, video_url, facebook_url, twitter_handle, brochure_link_text, brochure_type, brochure, brochure_url, local_info_feed, listing_image, listing_title, listing_text, overview_title, overview_text, overview_bullet_1, overview_bullet_2, overview_bullet_3, features_1_title, features_1_text, features_2_title, features_2_text, features_3_title, features_3_text, neighborhood_text, contact_text, show_lead_2_lease, lead_2_lease_email, published
    options:
      ckeditor: listing_text, overview_text, features_1_text, features_2_text, features_3_text, neighborhood_text, contact_text
      booleans:
        published: ['Yes', 'No']
      selectors: brochure_type
      destroy_related: PropertySlideshow, PropertyMiniSlideshow, Video, PhotoSet, ApartmentFloorPlan
  order_by: title
  relationships: property_features, city, county, local_info_feed, slideshow, mini_slideshow, videos, photo_set, floor_plans
  filters:
  search: title, street_address
  application: Properties

ApartmentFloorPlan:
  fields:
    default: name, bedrooms, bathrooms, featured, position
    list: actual_image, bedrooms, bathrooms, position
    form: name, featured, image_type, image_url, image, availability_url, bedrooms, bathrooms, min_square_feet, max_square_feet, min_market_rent, max_market_rent, min_effective_rent, max_effective_rent, floor_plan_group
    options:
      selectors: image_type
      booleans:
        featured: ['Yes', 'No']
  order_by: floor_plan_group_id, position
  relationships: floor_plan_group
  filters:
  search:
  application:

ApartmentFloorPlanGroup:
  fields:
    default: name, position
    list: name, position
    form: name
  order_by: position
  relationships: floor_plans
  search: name
  application:

Award:
  fields:
    default: title, published, published_at, section
    list: title, published, published_at, section
    form: title, body, published, published_at, section
    options:
      ckeditor: body
  order_by: 
  relationships: section
  filters:
  search: title
  application: Content

BodySlide:
  fields:
    default: image, position
    list: image, position
    form: image, body_slideshow
  order_by: position
  relationships: body_slideshow
  filters: 
  search: 
  application: 

BodySlideshow:
  fields:
    default: name
    list: name, page
    form: name, page
  order_by: 
  relationships: page, slides
  filters: 
  search: name
  application: 

City:
  fields:
    default: name, state
    list: name, state
    form: name, state
  order_by: name
  relationships: apartment_communities, counties, state
  filters:
  search: name
  application: Geography

County:
  fields:
    default: name, state
    list: name, state
    form: name, state
  order_by: name
  relationships: state, cities
  filters:
  search: name
  application: Geography

Feed:
  fields:
    default: name, url
    list: name, url
    form: name, url
  order_by:
  relationships: 
  filters:
  search:
  application:

Home:
  fields:
    default: name, bedrooms, bathrooms, featured, position
    list: name, bedrooms, bathrooms, home_community, position
    form: name, bedrooms, bathrooms, featured, home_community
    options:
      destroy_related: HomeFloorPlan
  order_by: position
  relationships: home_community, floor_plans
  filters:
  search: name
  application:

HomeCommunity:
  fields:
    default: title, published, street_address, city
    list: title, published, street_address, city
    form: title, short_title, meta_title, meta_description, meta_keywords, street_address, city, county, phone_number, latitude, longitude, website_url, video_url, facebook_url, twitter_handle, brochure_link_text, brochure_type, brochure, brochure_url, local_info_feed, listing_image, listing_title, listing_text, latitude, longitude, overview_title, overview_text, overview_bullet_1, overview_bullet_2, overview_bullet_3, features_1_title, features_1_text, features_2_title, features_2_text, features_3_title, features_3_text, neighborhood_text, contact_text, published
    options:
      ckeditor: listing_text, overview_text, features_1_text, features_2_text, features_3_text, neighborhood_text, contact_text
      booleans:
        published: ['Yes', 'No']
      selectors: brochure_type
      destroy_related: PropertySlideshow, PropertyMiniSlideshow, Home
  order_by: title
  relationships: property_features, city, county, slideshow, mini_slideshow, homes, local_info_feed
  filters: 
  search: title
  application: Properties

HomeFloorPlan:
  fields:
    default: name, image, position
    list: name, position
    form: name, image, home
  order_by: position
  relationships: home
  filters:
  search: name
  application:

HomePage:
  fields:
    default: featured_property
    list: featured_property
    form: meta_title, meta_description, meta_keywords, body, featured_property
    options:
      ckeditor: body
      destroy_related: HomePageSlide
  order_by: 
  relationships: featured_property, slides
  filters: 
  search: 
  application: Content

HomePageSlide:
  fields:
    default: image, position
    list: image, position
    form: image
  order_by: position
  relationships: home_page
  filters: 
  search: 
  application: 

LandingPage:
  fields:
    default: title, state
    list: title, state
    form: title, state, meta_title, meta_description, meta_keywords, masthead_body, masthead_image, secondary_title, secondary_body
    options:
      ckeditor: masthead_body, secondary_body
  order_by: 
  relationships: state, popular_properties, apartment_communities, featured_apartment_communities, home_communities, projects
  filters: 
  search: title
  application: Geography

MastheadSlide:
  fields:
    default: image, image_link, position
    list: image, image_link, position
    form: body, slide_type, image, image_link, sidebar_text, featured_property, masthead_slideshow
    options:
      ckeditor: body, sidebar_text
      selectors: slide_type
  order_by: position
  relationships: featured_property, masthead_slideshow
  filters: 
  search: 
  application: 

MastheadSlideshow:
  fields:
    default: name
    list: name, page
    form: name, page
  order_by: 
  relationships: page, slides
  filters: 
  search: name
  application: 

NewsPost:
  fields:
    default: title, published, published_at
    list: title, published, published_at
    form: title, meta_title, meta_description, meta_keywords, body, published, published_at, section
    options:
      ckeditor: body
  order_by: -published_at
  relationships: section
  filters:
  search:
  application: Content

Page:
  fields:
    default: formatted_title, position
    list: formatted_title, section, position
    form: title, meta_title, meta_description, meta_keywords, body, section, parent
    options:
      ckeditor: body
      destroy_related: MastheadSlideshow, BodySlideshow
  order_by: section_id, lft
  relationships: parent, section, masthead_slideshow, body_slideshow
  filters:
  search: title
  application: 
  options:

Photo:
  fields:
    default: image, caption, apartment_community
    list: image, caption, apartment_community
    form: image, caption, apartment_community
  order_by:
  relationships: apartment_community
  filters:
  search:
  application:

PhotoSet:
  fields:
    default: title, flickr_set_number
    list: title, flickr_set_number, property
    form: flickr_set_number, property
  order_by: 
  relationships: property
  filters: 
  search: title
  application: 

Project:
  fields:
    default: title, published, street_address, city
    list: title, published, street_address, city
    form: title, short_title, meta_title, meta_description, meta_keywords, section, street_address, city, county, latitude, longitude, website_url, video_url, brochure_link_text, brochure_type, brochure, brochure_url, listing_image, listing_title, listing_text, overview_text, published
    options:
      ckeditor: listing_text, overview_text
      booleans:
        published: ['Yes', 'No']
      selectors: brochure_type
      destroy_related: PropertySlideshow, PropertyMiniSlideshow, ProjectDataPoint, ProjectUpdate
  order_by: title
  relationships: city, section, slideshow, mini_slideshow, data_points, updates, project_categories
  filters: 
  search: title
  application: Properties

ProjectCategory:
  fields:
    default: title
    list: title, position
    form: title
  order_by: position
  relationships: projects
  filters: 
  search: title
  application: Properties

ProjectDataPoint:
  fields:
    default: name, data, position
    list: name, data, position
    form: name, data, project
  order_by: position
  relationships: project
  filters:
  search: name
  application:

ProjectUpdate:
  fields:
    default: published_at, published
    list: published_at, published
    form: body, published, published_at, project
    options:
      ckeditor: body
  order_by: 
  relationships: project
  filters:
  search:
  application:

Property:
  fields:
    default: title, street_address, city
    list:
    form:
    options:
      selectors: brochure_type
  order_by: title
  relationships: slideshow, mini_slideshow, video, photo_set
  filters:
  search:
  application:

PropertyFeature:
  fields:
    default: name, icon
    list: name, icon
    form: name, icon, description
  order_by: position
  relationships: 
  filters: 
  search: name
  application: Properties

PropertyMiniSlide:
  fields:
    default: image, position, property_mini_slideshow
    list: image, position, property_mini_slideshow
    form: image, property_mini_slideshow
  order_by: position
  relationships: property_mini_slideshow
  filters: 
  search: 
  application: 

PropertyMiniSlideshow:
  fields:
    default: name, property
    list: name, property
    form: name, property
    options:
      destroy_related: PropertyMiniSlide
  order_by: 
  relationships: property, slides
  filters: 
  search: 
  application: 

PropertySlide:
  fields:
    default: image, position, property_slideshow
    list: image, position, property_slideshow
    form: image, caption, property_slideshow
  order_by: position
  relationships: property_slideshow
  filters: 
  search: 
  application: 

PropertySlideshow:
  fields:
    default: name, property
    list: name, property
    form: name, property
    options:
      destroy_related: PropertySlide
  order_by: 
  relationships: property, slides
  filters: 
  search: name
  application: 

Section:
  fields:
    default: title
    list: title
    form: title, left_montage_image, middle_montage_image, right_montage_image
    options:
      read_only: title
      destroy_related: Page, NewsPost, Testimonial, Project, Award
  order_by: title
  relationships: pages, news_posts, testimonials, awards, projects
  filters:
  search:
  application: Content

State:
  fields:
    default: name, code
    list: name, code
    form: name, code
  order_by: name
  relationships: cities, counties
  filters:
  search: name
  application: Geography

Testimonial:
  fields:
    default: name, title, quote
    list: name, title, quote
    form: name, title, quote, section
    options:
      ckeditor: quote
  order_by:
  relationships: section
  filters:
  search: name
  application: Content

Video:
  fields:
    default: url, position
    list: image, position, property
    form: image, url, property
  order_by: position
  relationships: property
  filters: 
  search: 
  application: 
