development:
  sms:
    username:
    password:
    sender:
  flickr:
    username: Bozzuto Group
    api_key: '8042a247ce230ca6fe328406b416b7a2' # Bozzuto's API key
  paperclip_command_path: /usr/local/bin
  walkscore_wsid: 'YOUR-WSID-HERE'
  google_maps_api_key: 'ABQIAAAA7txTDQDFqeDYcgMQiou82BS4HyMuMWnF1gYqzj4uDbvuvSLR0RQG2OmrjDwO9korkAMlXnDyKPNeTw' # key for bozzuto.local
  contact_emails:
    general_inquiry:
    apartments:
    new_homes:
    acquisitions:
    construction:
    development:
    homebuilding:
    land:
  sms:
    username: mkilmurry
    password: 120012
    sender: 39044      

production:
  walkscore_wsid: 'YOUR-WSID-HERE'
  sms:
    username: mkilmurry
    password: 120012
    sender: 39044

test:
  sms:
    username:
    password:
    sender:
  flickr:
    username: Bozzuto Group
    api_key: '8042a247ce230ca6fe328406b416b7a2' # Bozzuto's API key
  walkscore_wsid: 'YOUR-WSID-HERE'
  google_maps_api_key: 'ABQIAAAA7txTDQDFqeDYcgMQiou82BS4HyMuMWnF1gYqzj4uDbvuvSLR0RQG2OmrjDwO9korkAMlXnDyKPNeTw' # key for bozzuto.local
  contact_emails:
    general_inquiry:
    apartments:
    new_homes:
    acquisitions:
    construction:
    development:
    homebuilding:
    land:
  sms:
    username: tester
    password: 12345
    sender: 333333
