package_assets: on
embed_assets: off
compress_assets: on
javascript_compressor: yui

javascripts:
  jquery:
    - public/javascripts/vendor/jquery.min.js
  bozzuto:
    - public/javascripts/vendor/jquery.lightbox_me.js
    - public/javascripts/vendor/jquery.scrollTo-min.js
    - public/javascripts/vendor/jquery.json.js
    - public/javascripts/vendor/jquery.stickem.js
    - public/javascripts/vendor/jquery.metadata.js
    - public/javascripts/vendor/jmapping/StyledMarker.js
    - public/javascripts/vendor/jmapping/markermanager.js
    - public/javascripts/vendor/jmapping/jquery.jmapping.js
    - public/javascripts/vendor/jquery.validate.js
    - public/javascripts/vendor/jquery.makecolumnlists.js
    - public/javascripts/plugins/jquery.videoLightbox.js
    - public/javascripts/plugins/floodlight.js
    - public/javascripts/bozzuto.js
    - public/javascripts/analytics.js
    - public/javascripts/yelp-map.js
  lookup:
    - public/javascripts/vendor/lookup.js
  mobile:
    - public/javascripts/vendor/jquery.min.js
    - public/javascripts/analytics.js
  neighborhoods:
    - public/javascripts/vendor/markerwithlabel.js
    - public/javascripts/vendor/polyfill.object.create.js
    - public/javascripts/vendor/modernizr.min.js
    - public/javascripts/plugins/jquery.transitionend.js
    - public/javascripts/neighborhoods.js
    - public/javascripts/neighborhoods/map.js
    - public/javascripts/neighborhoods/overlay.js
    - public/javascripts/neighborhoods/spot.js
  redesign:
    - public/javascripts/redesign/vendor/jquery.metadata.js
    - public/javascripts/redesign/vendor/jquery.json.js
    - public/javascripts/redesign/vendor/jmapping/StyledMarker.js
    - public/javascripts/redesign/vendor/jmapping/markermanager.js
    - public/javascripts/redesign/vendor/jmapping/jquery.jmapping.js
    - public/javascripts/redesign/vendor/jquery.makecolumnlists.js
    - public/javascripts/redesign/vendor/jquery.lightbox_me.js
    - public/javascripts/redesign/vendor/jquery.browser.js
    - public/javascripts/redesign/plugins/jquery.videoLightbox.js
    - public/javascripts/redesign/plugins/jquery.lightbox.js
    - public/javascripts/redesign/application.js
    - public/javascripts/redesign/common.js
    - public/javascripts/redesign/analytics.js
    - public/javascripts/redesign/pages/apartment_communities.js
    - public/javascripts/redesign/yelp_map.js

stylesheets:
  bozzuto:
    - public/stylesheets/screen.css
  neighborhoods:
    - public/stylesheets/neighborhoods.css
  redesign:
    - public/stylesheets/application.css
    - public/stylesheets/pages/community.css
  mobile:
    - public/stylesheets/mobile.css
