package_assets: on
embed_assets: off
compress_assets: on
javascript_compressor: yui

javascripts:
  bozzuto:
    - public/javascripts/vendor/jquery.min.js
    - public/javascripts/vendor/jquery.lightbox_me.js
    - public/javascripts/vendor/jquery.scrollTo-min.js
    - public/javascripts/vendor/mapiconmaker.js
    - public/javascripts/vendor/markermanager.js
    - public/javascripts/vendor/jquery.metadata.js
    - public/javascripts/vendor/jquery.jmapping.min.js
    - public/javascripts/vendor/jquery.validate.js
    - public/javascripts/vendor/jquery.makecolumnlists.js
    - public/javascripts/bozzuto.js
  lookup:
    - public/javascripts/vendor/lookup.js

stylesheets:
  bozzuto:
    - public/stylesheets/screen.css
