package_assets: on
embed_assets: off
compress_assets: on
javascript_compressor: yui

javascripts:
  jquery:
    - public/javascripts/vendor/jquery.min.js
  bozzuto:
    - public/javascripts/vendor/jquery.lightbox_me.js
    - public/javascripts/vendor/jquery.scrollTo-min.js
    - public/javascripts/vendor/jquery.json.js
    - public/javascripts/vendor/jquery.metadata.js
    - public/javascripts/vendor/jmapping/StyledMarker.js
    - public/javascripts/vendor/jmapping/markermanager.js
    - public/javascripts/vendor/jmapping/jquery.jmapping.js
    - public/javascripts/vendor/jquery.validate.js
    - public/javascripts/vendor/jquery.makecolumnlists.js
    - public/javascripts/bozzuto.js
    - public/javascripts/analytics.js
    - public/javascripts/yelp-map.js
  lookup:
    - public/javascripts/vendor/lookup.js
  mobile:
    - public/javascripts/vendor/jquery.min.js
    - public/javascripts/analytics.js
  redesign:
    - public/javascripts/vendor/jquery.makecolumnlists.js
    - public/javascripts/redesign/application.js
    - public/javascripts/redesign/pages/apartment_communities.js

stylesheets:
  bozzuto:
    - public/stylesheets/screen.css
