class RemoveArchiveTables < ActiveRecord::Migration

  # These used to be generated by `acts_as_archive`, gem is now defunct.
  # This migration will remove the tables that may exist, previously 
  # generated with:
  #
  # `ActsAsArchive.update <model>`
  #
  # db/migrate/20110107152124_add_archive_table_for_pages.rb
  # db/migrate/20101229190836_add_archive_table_for_properties.rb
  
  def db_error_safe(&block)
    yield
  rescue => e
    # ignore
  end

  def up
    db_error_safe do
      execute "DROP TABLE archived_pages"
    end

    db_error_safe do
      execute "DROP TABLE archived_properties"
    end
  end

  def down
    raise ActiveRecord::IrreversibleMigration
  end
end
